services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simplesolat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # monosolat-api:
  #   image: ghcr.io/ragibkl/simplesolat-api:sha-9171512
  #   environment:
  #     DATABASE_URL: postgres://user:password@postgres/simplesolat_db
  #   ports:
  #     - 3000:3000

volumes:
  postgres_data:
